export const GET_PRODUCTS = 'GET_PRODUCTS';
export const HOT_TREND_PRODUCTS = 'HOT_TREND_PRODUCTS';
export const RECENTYLE_VIEWED_PRODUCTS = 'RECENTYLE_VIEWED_PRODUCTS';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
